import { Sparkles, GraduationCap } from "lucide-react";
import { RoadmapTimeline } from "../components/RoadmapTimeline";
import { Button, EmptyState, Page, Panel, SectionTitle, SkeletonBlock, StatusPill } from "../components/ui";
import { priorityClass } from "../lib/format";
import { useAnalysis } from "../state/analysis-store";
import { motion } from "framer-motion";

export function Roadmap() {
  const { comparison, roadmap, statuses, generateRoadmap } = useAnalysis();

  if (!comparison) {
    return (
      <Page>
        <EmptyState icon={GraduationCap} title="No comparison available" body="Run SkillLens first so the roadmap can use verified gaps and role context." />
      </Page>
    );
  }

  return (
    <Page>
      <div className="mb-12 flex flex-col gap-6 sm:flex-row sm:items-end sm:justify-between">
        <motion.div
          initial={{ opacity: 0, x: -20 }}
          animate={{ opacity: 1, x: 0 }}
        >
          <StatusPill tone="blue">Path to Mastery</StatusPill>
          <h1 className="mt-4 text-4xl font-bold tracking-tight text-ink sm:text-5xl">
            Career <span className="text-accent">Blueprint.</span>
          </h1>
          <p className="mt-4 max-w-2xl text-lg font-medium text-muted leading-relaxed">
            Personalized learning path for <span className="text-ink font-bold">{comparison.target_role}</span> based on your verified evidence gaps.
          </p>
        </motion.div>
        <motion.div
          initial={{ opacity: 0, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
        >
          <Button 
            size="lg"
            variant="accent"
            onClick={generateRoadmap} 
            disabled={statuses.roadmap === "loading"}
            className="w-full sm:w-auto"
          >
            <Sparkles size={18} />
            {roadmap ? "Refresh Roadmap" : "Generate Roadmap"}
          </Button>
        </motion.div>
      </div>

      <div className="grid gap-8 lg:grid-cols-[0.8fr_1.2fr]">
        <Panel>
          <SectionTitle 
            kicker="Target Areas" 
            title="Focus Skills" 
            description="The most critical competencies you need to bridge your current gap."
          />
          <div className="space-y-4">
            {(roadmap?.focus_skills.length ? roadmap.focus_skills : comparison.missing_skills).map((skill, index) => {
              const name = "skill" in skill ? skill.skill : skill.name;
              const rationale = "rationale" in skill ? skill.rationale : skill.reason;
              return (
                <motion.article 
                  key={name} 
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: index * 0.05 }}
                  className="rounded-2xl border border-line p-5 transition-all hover:border-accent/30 hover:bg-slate-50"
                >
                  <div className="flex items-center justify-between gap-3">
                    <p className="font-bold text-ink">{name}</p>
                    <span className={`rounded-full border px-3 py-1 text-[10px] font-bold uppercase tracking-widest ${priorityClass(skill.priority)}`}>{skill.priority}</span>
                  </div>
                  <p className="mt-4 text-sm font-medium leading-relaxed text-muted">{rationale}</p>
                </motion.article>
              );
            })}
          </div>
        </Panel>

        <Panel>
          <SectionTitle 
            kicker="Progression" 
            title="Milestones" 
            description="A step-by-step timeline generated by our RAG-enhanced mentor engine."
            action={roadmap ? <StatusPill tone="good">Optimized</StatusPill> : <StatusPill>Pending</StatusPill>} 
          />
          {statuses.roadmap === "loading" ? (
            <div className="space-y-4">
              {[0, 1, 2].map((item) => (
                <SkeletonBlock key={item} className="h-40" />
              ))}
            </div>
          ) : roadmap ? (
            <RoadmapTimeline roadmap={roadmap} />
          ) : (
            <EmptyState title="Roadmap Not Generated" body="Generate a Groq-backed plan using your comparison and the learning/job RAG context." />
          )}
        </Panel>
      </div>

      {roadmap ? (
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3 }}
          className="mt-8"
        >
          <Panel>
            <SectionTitle kicker="Application" title="Portfolio Projects" description="Real-world projects designed to prove your newly acquired skills." />
            <div className="grid gap-4 md:grid-cols-3">
              {roadmap.portfolio_projects.map((project, index) => (
                <motion.div 
                  key={project} 
                  whileHover={{ y: -5 }}
                  className="rounded-2xl border border-line bg-slate-50/50 p-6 text-sm font-medium leading-relaxed text-muted hover:border-accent/30 hover:bg-white hover:shadow-soft"
                >
                  <span className="mb-4 block h-8 w-8 rounded-lg bg-white text-center font-bold text-accent shadow-sm ring-1 ring-line">
                    {index + 1}
                  </span>
                  {project}
                </motion.div>
              ))}
            </div>
            <div className="mt-8 rounded-2xl bg-ink p-8 text-white shadow-xl">
               <div className="flex items-center gap-3 mb-4">
                 <div className="h-8 w-8 rounded-full bg-accent flex items-center justify-center">
                    <Sparkles size={16} />
                 </div>
                 <p className="text-xs font-bold uppercase tracking-widest text-slate-400">Mentor Note</p>
               </div>
               <p className="text-lg font-medium leading-relaxed italic opacity-90 text-slate-200">"{roadmap.mentor_note}"</p>
            </div>
          </Panel>
        </motion.div>
      ) : null}
    </Page>
  );
}
